name: Deploy build on lactame.com

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

env:
  NODE_VERSION: 16.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.published) }}"
      - uses: actions/checkout@v3
      - name: Get package name
        run: echo "PACKAGE_NAME=package1" >> $GITHUB_ENV
      - name: Set current folder name
        run: echo "CURRENT_FOLDER=packages/{{ env.PACKAGE_NAME }}" >> $GITHUB_ENV
      - name: Build name
        run: echo "BUILD_NAME=$(jq .${{ env.PACKAGE_NAME }} lactame.json | tr -d '"')" >> $GITHUB_ENV
      - if: ${{ env.BUILD_NAME }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npx cheminfo-build --cwd ${{ env.CURRENT_FOLDER }} --entry index.js --root TestMulti
      - name: Deploy to lactame.com
        uses: zakodium/lactame-action@v1
        with:
          token: ${{ secrets.LACTAME_TOKEN }}
          name: ${{ env.PACKAGE_NAME }}
          folder: ${{ env.CURRENT_FOLDER }}/dist
