name: Deploy build on lactame.com

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

env:
  NODE_VERSION: 16.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.published) }}"
      - uses: actions/checkout@v3
      - name: Set current folder name
        run: echo "CURRENT_FOLDER=packages/package1 | tr -d '"')" >> $GITHUB_ENV
      - name: Get package name
        run: echo "PACKAGE_NAME=$(jq .name ${{ env.CURRENT_FOLDER }}/package.json | tr -d '"')" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: cheminfo-build --cwd packages/package1 --entry index.js --root TestMulti"
      - name: Deploy to lactame.com
        uses: zakodium/lactame-action@v1
        with:
          token: ${{ secrets.LACTAME_TOKEN }}
          name: ${{ env.PACKAGE_NAME }}
          folder: dist
